### PR TITLE
fix: Add guard if OUTPUT_FOLDER exists or not before creating it

### LINKED ISSUE #30: Output folder cannot be created if exists and action fails
If the `OUTPUT_FOLDER` is configured and does already exist, than the action runs into an error, because https://github.com/Decathlon/release-notes-generator-action/blob/master/entrypoint.sh#L60 `mkdir $OUTPUT_FOLDER` cannot run. We need a guard to check if the folder is already there or not.

Error message:
```
mkdir: can't create directory '.chglog': File exists
```

So we could replace the line with
```
[ ! -d "$OUTPUT_FOLDER" ] && mkdir $OUTPUT_FOLDER"
```

### PR DESCRIPTION
**Pull request by derTobsch**
closes #30

### CODE REVIEW

**Comment by GregoireW** [comment]
I would have set a "mkdir -p $OUTPUT_FOLDER"    which cover more usecase.

**Comment by GregoireW** [comment]
```
   [ ! -d "$OUTPUT_FOLDER" ] && mkdir $OUTPUT_FOLDER
```

can be replaced by 

```
   mkdir -p $OUTPUT_FOLDER
```

(and I'm not Marco ;) )

**Comment by derTobsch** [comment]
> ```
>    [ ! -d "$OUTPUT_FOLDER" ] && mkdir $OUTPUT_FOLDER
> ```
> 
> can be replaced by
> 
> ```
>    mkdir -p $OUTPUT_FOLDER
> ```
> 
> (and I'm not Marco ;) )

Yes I know. But this is not your repository that is why I asked @mmornati how he want it :)

**Comment by mmornati** [comment]
@derTobsch I guess we trust @GregoireW 😅 Is one of our top Staf Engineer in Decathlon.
I will make a review to give a personal advice.

**Review by mmornati — COMMENTED** [review]
Quite agree with @GregoireW. In the end you are right and it is cool to have proposed this PR to secure the way the plugin is working. The `mkdir - p` is just assuring that the whole path is created in case we are asking to write into a une sting path.

Then just a side comment, we are using this path as output folder for the release note and passing this path to the Docker.
I didn't made any directory creation bacause in my mind was quite strange to provide to the Docker a missing folder.
Then @GregoireW what about Docker right folder on the host with the `-p` parameter? Will be Docker able to create a full path on a "file system" which is not controlling?

Maybe we can simple brake the workflow is the parameter is provided but it is not a dir or it is not existing? With a message like "you should provide a valid folder". Is that make sens?

**Comment by derTobsch** [comment]
For me both would be ok. We already provide the directory. 

If we just want to notify the users we could go with.

```bash
#Output folder configuration
if [ -z "$OUTPUT_FOLDER" ]; then
  echo "OUTPUT_FOLDER ENV is missing, using the default one"
  exit 1
fi
```

That would be a breaking change and I would prefer not to break to much for this little effort. So for this fix I think we should just add a warning like that one already defined and go with `mkdir -p`

**Comment by GregoireW** [comment]
@mmornati Currently you use a docker image with default user to root. GitHub do not (yet?) force the user at runtime. You will not have any issue to create the directory. 

If you run this action on self hosted runner you will have to delete this directory (using a root user via a docker or via `su`)  at the end of the workflow. Else a new workflow of the same repo, on the same runner will make the checkout action crash. (but this is the same issue with a lot of docker action)

**Comment by mmornati** [comment]
On go with the `-p` proposed. And I can merge and create a new release.

**Comment by derTobsch** [comment]
> On go with the `-p` proposed. And I can merge and create a new release.

There it is :)

**Comment by derTobsch** [comment]
@mmornati piing :D

**Comment by mmornati** [comment]
> @mmornati piing :D

Sorry. I need to understand why I'm notified only when is @GregoireW which is answering :) Merging it and making a new release

**Comment by mmornati** [comment]
> @mmornati piing :D

Sorry. I need to understand why I'm notified only when is @GregoireW who is answering :) Merging it and making a new release

**Review by mmornati — APPROVED** [review]

**Pull request merged**
